spring.application.name=ecom-application
server.port=8082
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create
management.endpoints.web.exposure.include=beans, health
spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb
spring.datasource.username=joreid
spring.datasource.password=joreid
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
